version: '3'
services:
  proxy:
    container_name: runningproxy
    hostname: proxy
    image: proxy
    ports:
      - 443:443
    networks:
      - backend
      - frontend
  web:
    container_name: runningweb
    hostname: web
    image: web
    networks:
      - backend
      
networks:
  frontend:
  backend:
    